all: task3

task1:
	gcc task1.c -o task1
	./task1
	rm task1

task4:
	gcc task4.c -o task4
	./task4
	rm task4

task5:
	gcc task5.c -o task5
	./task5
	rm task5

task3:
	gcc task3.c -o task3
	./task3
	rm task3